### ISSUE TITLE
hooks don't work for custom compile dirs

### ISSUE THREAD

**Issue by oblitzitate** [udayvir-singh/tangerine.nvim#12]
Onsave compilation doesn't work when in awesome dir, but works when in nvim dir

Here's the awesome compile dir config:
```lua
  local awesome_dir = os.getenv("HOME") .. "/.config/awesome"
  _G.tangerine.api.compile.dir(
    awesome_dir .. "/fnl",
    awesome_dir .. "/lua",
    {
      globals = vim.list_extend(vim.tbl_keys(_G), {
        "awesome",
        "root",
        "modkey",
        "RC"
      }),
      hooks = { "onsave", "oninit" },
      verbose = true,
    }
  )
```

**Comment by udayvir-singh** [comment]
@oblitzitate 

`tangerine.api.compile.dir` is just a function in module [compile.fnl](https://github.com/udayvir-singh/tangerine.nvim/blob/master/fnl/tangerine/api/compile.fnl) hence it has no bindings to vim's api, bindings are done in module [hooks.fnl](https://github.com/udayvir-singh/tangerine.nvim/blob/master/fnl/tangerine/vim/hooks.fnl) that's why hooks are not working [it is done by design].

You have to create hooks manually for custom dirs:
```lua
local awesome_dir = os.getenv("HOME") .. "/.config/awesome"

function compile_awesome()
  return _G.tangerine.api.compile.dir(
    awesome_dir .. "/fnl",
    awesome_dir .. "/lua",
    {
      globals = vim.list_extend(vim.tbl_keys(_G), {
        "awesome",
        "root",
        "modkey",
        "RC"
      }),
      verbose = true,
    }
  )
end

-- on-init hook
compile_awesome()

-- on-save hook
local augid = vim.api.nvim_create_augroup("awesome-onsave", { clear = true })

vim.api.nvim_create_autocmd("BufWritePost", {
    group    = augid,
    pattern  = awesome_dir .. "/fnl/*.fnl",
    callback = compile_awesome,
})
```

**Comment by udayvir-singh** [comment]
@oblitzitate 

Just added new feature to allow compilation of custom dirs, and hooks are supported too.

Add these lines to your vimrc:
```lua
require [[tangerine]].setup {
  ...

  custom = {
    {"~/.config/awesome/fnl", "~/.config/awesome/lua"}
  }
}
```

see `:h tangerine.api.compile.custom()` for more info.
